export const LIVE_FUNDS_ENABLED = false as const;

export const MOCK_BANNER = "MOCK SETTLEMENT · NO FUNDS WILL MOVE" as const;

export const SUCCESS_PATH = [
  "QUOTED",
  "USDC_RESERVED",
  "INPUT_AUTHORIZED",
  "XENTS_ROUTED",
  "NFT_TRANSFER_PENDING",
  "NFT_TRANSFER_CONFIRMED",
  "USDC_RELEASED",
  "RECEIPT_FINALIZED",
] as const;

export const TERMINAL_STATES = [
  "QUOTE_EXPIRED",
  "INPUT_FAILED",
  "INSUFFICIENT_LIQUIDITY",
  "NFT_OWNERSHIP_CHANGED",
  "NFT_TRANSFER_FAILED",
  "CHAIN_CONFIRMATION_TIMEOUT",
  "USDC_PAYOUT_FAILED",
  "REFUND_PENDING",
  "REFUNDED",
  "MANUAL_REVIEW",
] as const;

export type SuccessState = (typeof SUCCESS_PATH)[number];
export type TerminalState = (typeof TERMINAL_STATES)[number];
export type SettlementState = SuccessState | TerminalState;

export const ALLOWED_TRANSITIONS: Record<SettlementState, readonly SettlementState[]> = {
  QUOTED: ["USDC_RESERVED", "QUOTE_EXPIRED", "INSUFFICIENT_LIQUIDITY", "MANUAL_REVIEW"],
  USDC_RESERVED: ["INPUT_AUTHORIZED", "INPUT_FAILED", "QUOTE_EXPIRED", "MANUAL_REVIEW"],
  INPUT_AUTHORIZED: ["XENTS_ROUTED", "INSUFFICIENT_LIQUIDITY", "REFUND_PENDING", "MANUAL_REVIEW"],
  XENTS_ROUTED: ["NFT_TRANSFER_PENDING", "NFT_OWNERSHIP_CHANGED", "REFUND_PENDING", "MANUAL_REVIEW"],
  NFT_TRANSFER_PENDING: [
    "NFT_TRANSFER_CONFIRMED",
    "NFT_TRANSFER_FAILED",
    "CHAIN_CONFIRMATION_TIMEOUT",
    "MANUAL_REVIEW",
  ],
  NFT_TRANSFER_CONFIRMED: ["USDC_RELEASED", "USDC_PAYOUT_FAILED", "MANUAL_REVIEW"],
  USDC_RELEASED: ["RECEIPT_FINALIZED"],
  RECEIPT_FINALIZED: [],
  QUOTE_EXPIRED: [],
  INPUT_FAILED: [],
  INSUFFICIENT_LIQUIDITY: ["REFUND_PENDING"],
  NFT_OWNERSHIP_CHANGED: ["REFUND_PENDING"],
  NFT_TRANSFER_FAILED: ["REFUND_PENDING", "MANUAL_REVIEW"],
  CHAIN_CONFIRMATION_TIMEOUT: ["MANUAL_REVIEW", "REFUND_PENDING"],
  USDC_PAYOUT_FAILED: ["MANUAL_REVIEW"],
  REFUND_PENDING: ["REFUNDED", "MANUAL_REVIEW"],
  REFUNDED: [],
  MANUAL_REVIEW: [],
};

export function isTerminal(state: SettlementState): boolean {
  return (TERMINAL_STATES as readonly string[]).includes(state) && ALLOWED_TRANSITIONS[state].length === 0;
}
